### ISSUE TITLE
「Instance Tickerを使う」を「インスタンス情報を表示」に変更したほうが良いと思う

### ISSUE THREAD

**Issue by weepjp** [pantasystem/Milktea#1121]
タイトルをドジって恥ずかしい。

## 困っていること

[#InstanceTicker](https://github.com/InstanceTicker/InstanceTicker) っていうものを作ったひとなんです。

Misskey および めいすきーでは、気を遣ってか「インスタンス情報」という分かりやすい名称を用いています。

なので、そっちを使われたほうが「Instance Ticker？なんそれ？」と思われなくなるとともに、[#InstanceTicker](https://github.com/InstanceTicker/InstanceTicker) そのものを利用・流用しているのではないかという、誤解が産まなくなりそうです。

## 画面名、機能名など（任意）

- 「Instance Ticker」を「インスタンス情報」にする。または、独自の機能名をつけるなど。
- こっちは「半角スペース」があることで、[#InstanceTicker](https://github.com/InstanceTicker/InstanceTicker) と区別していますと、言い張るならそれでもいいですが、作ったものとしてはそれはそれでちょっとうれしい話なんで、それも良かです。
- まぁ、気楽に考えて下さい。

**Comment by pantasystem** [comment]
良さそう

**Comment by pantasystem** [comment]
このIssueにアサインして直接コントリビュートされる予定はありますか？

**Comment by weepjp** [comment]
ないです
