### ISSUE TITLE
CW指定時にもっと見るボタンがnull文字になる

### ISSUE THREAD

**Issue by usbharu** [pantasystem/Milktea#1197]
## 不具合の概要
CW指定時にnull文字になる

## 再現方法
- どれかのクライアントでCW指定された本文が0文字のファイル付きノートを投稿する
- 投稿を見る

## 期待する動作
1ファイル などのファイルの数もしくは0文字
## Screenshots
![Screenshot_2023-01-12-19-58-25-69_af62dd2377a56e2f48f508abe6640edf](https://user-images.githubusercontent.com/64310155/212049849-a33b2f30-76b2-43d2-b9fc-0eecca99f1a3.jpg)

## 不具合が発生した時の端末
 - Device: OPPO Reno3 A / Amazon Fire HD 8 Plus 10世代
 - OS Version: Android 11 ベース Color OS V11 / Android 9 ベース FireOs 7.3.2.6
 - App Version: v2.46.0

## 備考　
Misskeyのwebクライアントでは1ファイルと表示されています。

**Comment by pantasystem** [comment]
メモ

該当実装箇所
https://github.com/pantasystem/Milktea/blob/develop/modules/features/note/src/main/java/net/pantasystem/milktea/note/view/ContentFoldingHelper.kt#L31

**Comment by pantasystem** [comment]
コントリビュートを希望しますか？

**Comment by usbharu** [comment]
お任せします。
