### ISSUE TITLE
検索の「見つける」で自分自身をフォローするボタンが出てくる

### ISSUE THREAD

**Issue by usbharu** [pantasystem/Milktea#1312]
## 不具合の概要
検索→見つける の欄で、自分自身が表示されている場合、フォローボタンが存在する。

## 再現方法
- 投稿する
- 検索→見つける→最近投稿したユーザーを見る

## 期待する動作
フォローボタンが存在しない、または見た目上でも無効

## Screenshots
![Screenshot_2023-01-29-14-35-14-92_af62dd2377a56e2f48f508abe6640edf](https://user-images.githubusercontent.com/64310155/215307493-799f25cc-8aa7-436a-8846-87af37dbf5dd.jpg)

## 不具合が発生した時の端末
 - Device: OPPO Reno3 A
 - OS Version: Android 11 ベース ColorOS V11
 - App Version: v2.66.4

## 備考
押しても何も起こらない

**Comment by pantasystem** [comment]
修正します
