### ISSUE TITLE
URLの概要非表示がTL上で流れてくる

### ISSUE THREAD

**Issue by nenohi** [pantasystem/Milktea#1339]
## 不具合の概要
`?[ULR](URL)`を投稿した際にTL上では概要が表示されてしまう
詳細画面に行くと概要が表示となり正常な動作となっている
## 再現方法
**不具合の再現方法を箇条書きで記述してください**
・`?[https://github.com/misskey-dev/misskey](https://github.com/misskey-dev/misskey)`の投稿を行う
・上記の投稿がTL上に流れてくる
・該当の投稿にURLの概要が表示される
## 期待する動作
・`?[https://github.com/misskey-dev/misskey](https://github.com/misskey-dev/misskey)`の投稿を行う
・上記の投稿がTL上に流れてくる
・?であるため該当投稿のURL概要が表示されない
## Screenshots
**不具合が発生した時のスクリーンショットやキャプチャー**
・TL上のキャプチャ
https://s3.arkjp.net/misskey/53e99dc2-ef40-441e-9a3b-286a745d778a.png
・ノート詳細のキャプチャ
https://s3.arkjp.net/misskey/65791fff-9052-4da1-acb6-1dfc04785c47.png
## 不具合が発生した時の端末
 - Device:Pixel 6 Pro
 - OS Version:Android13
 - App Version:266.4

**Comment by pantasystem** [comment]
URLの概要とはOGPの表示のことで間違い無いでしょうか？
また概要非表示とはURLのオプションの頭にクエスチョンをつけることを意味しているということで間違い無いでしょうか？

**Comment by nenohi** [comment]
> URLの概要とはOGPの表示のことで間違い無いでしょうか？
はい、間違いないです
> また概要非表示とはURLのオプションの頭にクエスチョンをつけることを意味しているということで間違い無いでしょうか？
はい、現状のMisskeyWebクライアントの仕様上`?[URL](URL)`構文では概要は表示されないことになっております
