### ISSUE TITLE
Image Caption指定しても適用されない

### ISSUE THREAD

**Issue by saschanaz** [pantasystem/Milktea#1419]
## 不具合の概要

タイトルどおり

## 再現方法
**不具合の再現方法を箇条書きで記述してください**

1. 映像を選択します
2. Captionを編集します
3. アップロードします
4. Webでcaptionが見えるのか確認します

## 期待する動作

Captionが見える

## Screenshots
**不具合が発生した時のスクリーンショットやキャプチャー**

## 不具合が発生した時の端末
 - Device: Galaxy S22 Ultra
 - OS Version: Android 13
 - App Version: 2.86.1

**Comment by pantasystem** [comment]
Misskeyですか？Mastodonですか？

**Comment by saschanaz** [comment]
Misskey 13です!
