### ISSUE TITLE
フォローし忘れユーザ一覧を作成する

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1432]
# 概要
個人的な思想としてLTLで空リプの送り合いをするのではなく
気に入ったユーザ絡みのある人はフォローしていってもらって
フォローを構築してもらい、いずれ他サーバに移行した時にフォローインポートしやすくしたいという思惑がある。
そこで普段よくリアクションしている相手で未フォローユーザがいる場合そのユーザをおすすめなどに出すようにしたい。

**Comment by tateisu** [comment]
Mastodonの「フォロー推奨ユーザ」APIがそんな感じで、実質的に「フォローし忘れユーザ一覧」だった

**Comment by pantasystem** [comment]
おーMastodonにはそんな機能があるんですね
