### ISSUE TITLE
Can't authenticate on Calckey dev branch

### ISSUE THREAD

**Issue by ThatOneCalculator** [pantasystem/Milktea#1441]
On Calckey's dev branch, we added Mastodon API compatibility (original Misskey API is still there), but Milktea seems to be confused when logging into Calckey. It loads the MiAuth page, but doesn't log in after clicking Accept. 

 - Instance: stop.voring.me
 - Device: Pixel 6
 - OS Version: 13
 - App Version: 

```
version v2.90.1

jp.panta.misskeyandroidclient
versionCode 1874

targetSdk 33
minSdk 21

Installed: Jan 24, 2023; 11:15 AM
Updated: Feb 18, 2023; 12:22 PM
```

**Comment by pantasystem** [comment]
Do verifiable instances exist?

**Comment by ThatOneCalculator** [comment]
https://stop.voring.me runs the latest version of the Calckey development branch, so you can use it for testing :)

**Comment by ThatOneCalculator** [comment]
I can confirm it works now as of the latest update, thank you for fixing it quickly ❤️

![Screenshot_20230221-121703.png](https://user-images.githubusercontent.com/44733677/220449201-a97b959d-a835-4d1b-b3f0-e259fcbaedc0.png)
