### ISSUE TITLE
Instance Tickerの表示とユーザー名がモロにかぶる

### ISSUE THREAD

**Issue by digitalsp** [pantasystem/Milktea#1451]
## 不具合の概要
InstanceTickerとユーザー名が被って表示される

## 再現方法
特になし(普通に使っていると時々発生する)

## 期待する動作
被らずに表示される

## Screenshots
![Screenshot_2023-02-21-09-00-31-011_jp.panta.misskeyandroidclient-edit.jpg](https://user-images.githubusercontent.com/82262872/220215595-3fbf8cb5-d4e6-48e1-acb0-de3ccf68c84c.jpg)

## 不具合が発生した時の端末
 - Device:Xiaomi 12S Ultra
 - OS Version:MIUI 14.0.5(Android 13)
 - App Version:v2.95.1-alpha2

## 備考　
root化済み、LSPosedモジュール導入済み端末(Milkteaには適用していません)

**Comment by digitalsp** [comment]
![Screenshot_2023-02-21-09-53-53-716_jp.panta.misskeyandroidclient-edit.jpg](https://user-images.githubusercontent.com/82262872/220221288-c73532fe-91c5-4f01-b439-c23d001c1eff.jpg)

ユーザー名に:ifilter_misetehoshii:などの横長絵文字を使うとまた違うバグり方をするみたいです(一応報告)

**Comment by pantasystem** [comment]
ユーザー名をデフォルト表示にすると発生するようですね

**Comment by pantasystem** [comment]
発生条件としては
- アプリ初回起動時
- 名前にカスタム絵文字のみが使われている
- usernameを左側表示にしている
- 画像が読み込まれていない
初期起動時は正しく絵文字が描画することができない不具合がありその影響でレイアウトがうまくできていないようです

**Comment by pantasystem** [comment]
ぐあああああああああああdevelopにプッシュしてしまったorz

**Comment by pantasystem** [comment]
画像み読み込み時にテキストの高さが未指定なのが原因でした。
https://github.com/pantasystem/Milktea/commit/a657df8995de5ac6233d5dc76d9bcf64f91a5ba9

**Comment by digitalsp** [comment]
直ったっぽいです、ありがとうございます。

**Comment by pantasystem** [comment]
一旦Closeにします。
同様の事例やその他不具合が発生したらまたお問合せください。
報告ありがとうございました。
