### ISSUE TITLE
ノート表示・ユーザ表示画面からアカウントを切り替えて表示しなおしたい

### ISSUE THREAD

**Issue by kazu0617** [pantasystem/Milktea#1463]
**Is your feature request related to a problem? Please describe.**
現在この操作を実現するために切り替えたいアカウントに対し`https://<host>/<accountname>`を「共有」から取得し、その値を`@<accountname>@<host>` に手入力で修正、投稿後切り替えたいアカウントにMilkteaを切り替えてクリックして表示をする必要があり、煩雑。

**Describe the solution you'd like**
ノート表示・ユーザ表示画面にあるプルダウンメニュー(…のやつ)からアカウントを切り替えて表示がしたい

**Describe alternatives you've considered**
上の問題に記載した操作を実施すれば可能。

**Additional context**
いい感じの画像が必要なら張ります。

**Comment by pantasystem** [comment]
ノート表示に関しては公開範囲の都合があるため場合によっては切り替えられないケースが考えられるのですが
ユーザに関しては可能なのと以前に検討していたので何実装したいです。
https://github.com/pantasystem/Milktea/issues/989

**Comment by pantasystem** [comment]
ちなみにアカウントを切り替える場合
画面単位の切り替えかそれともアプリ全体の切り替えどちらが良いと思いますか？

**Comment by pantasystem** [comment]
他の機能がアプリ全体での切り替えになるのに
画面だけでの切り替えになるのは少し分かりづらくなってしまうか？・・・

**Comment by kazu0617** [comment]
> 

個人的には他の実装に合わせてアプリ全体の切り替えが良いかなと思っています。

**Comment by pantasystem** [comment]
実現の可能性を検討した結果
現時点のMilkteaでは投稿詳細画面で横スワイプで
遷移元のタイムラインを見ることができるようにしているのですが
この機能とアカウント切り替えの相性が悪く技術的難易度が高いため
実装はしばらく先になってしまう可能性がありますがご了承ください🙇

**Comment by pantasystem** [comment]
切り替え時にap resolveを行なって
成功した場合はアカウントの切り替えを行う。
