### ISSUE TITLE
タブに追加することを意味するアイコンを共通化する

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1545]
# 概要
現状タブに追加可能な要素にタブに追加するためのボタンを設置しているが
機能によって指定されているアイコンがバラバラでUX的に微妙な感じになっているので、
アイコンを一つに共通化してわかりやすくしたい。

**Comment by sanao1006** [comment]
パッと見た感じ
1. ic_add(remove)_to_tab.xml: ユーザー詳細画面のヘッダー、アンテナ、検索結果(タイムライン、ユーザー)
![image](https://github.com/pantasystem/Milktea/assets/62137820/05d79251-e793-48f8-a5ec-2c2bdcca70e6)
2. boookmarkAdd(Remove): リスト、クリップ、チャンネル、タブ追加ボタン
![image](https://github.com/pantasystem/Milktea/assets/62137820/954832a5-975b-4464-8ea0-0eedc7b68fe8)
3. ic_add_black_24dp.xml: ノート詳細画面のみ？
![image](https://github.com/pantasystem/Milktea/assets/62137820/9052b3d2-e62e-4b29-b04a-d8eb8996dbef)

ですかね。
「タブを追加する」ボタンがBookmarkアイコンなのでBookmarkアイコンに統一しましょうか？

**Comment by pantasystem** [comment]
boookmarkAddにしている理由としては、
実装時の気分でImageVectorを使った方が楽だったのでこのようにしているのですが
ic_add(remove)_to_tabの方が見た目的にはわかりやすいそうだと思っているのですが
どう思われますか？

**Comment by sanao1006** [comment]
実装上問題なさそうなのでic_add(remove)_to_tabでよさそうですね。

僕個人としてもic_add(remove)_to_tabの方が分かりやすいと思います！

**Comment by pantasystem** [comment]
では、ic_add(remove)_to_tabへの置き換えお願いできますか？🙇
