### ISSUE TITLE
通知欄の絵文字が表示されなくなることがある

### ISSUE THREAD

**Issue by digitalsp** [pantasystem/Milktea#1557]
## 不具合の概要
Milkteaを起動させたまま、しばらくバックグラウンドにし再びアクティブにすると、通知欄の自分の投稿へのリアクションのカスタム絵文字が表示されなくなる(`:emoji_name:`のように文字で表示される)
リロードしてもそのままになる(再起動で直る)

## 再現方法
Milkteaを起動させたまま、しばらくバックグラウンドにし再びアクティブにする(調査不足)

## 期待する動作
絵文字が表示される

## Screenshots
![Screenshot_2023-03-22-22-23-29-105_jp.panta.misskeyandroidclient-edit.jpg](https://user-images.githubusercontent.com/82262872/226918201-d08ebad8-9dc4-472c-9c24-597e8224bfd5.jpg)

## 不具合が発生した時の端末
 - Device:Xiaomi 12S Ultra
 - OS Version:Android 13
 - App Version:v2.102.2-alpha9

**Comment by digitalsp** [comment]
![Screenshot_2023-03-22-23-14-30-325_jp.panta.misskeyandroidclient-edit.jpg](https://user-images.githubusercontent.com/82262872/226932242-b7317151-8f75-4cf1-9287-2b89e0ea2b2a.jpg)

(件の不具合が起きていない状態で)タスクキルしてアプリを再起動すると、逆に通知欄のカスタム絵文字が表示されなくなる現象が起こったので、バックグラウンド云々は直接の原因では無いかもしれません…？

**Comment by pantasystem** [comment]
すみません新たに発生した不具合です
報告ありがとうございます。

**Comment by digitalsp** [comment]
v2.102.2-alpha19にアップデートしたら直った気がします(追加したのに絵文字ピッカーに表示されなかった絵文字が表示されるようになったのと、通知欄の絵文字も今のところ正常)
クローズしてもらってかまいません

**Comment by pantasystem** [comment]
無事に解決できたみたいでよかったです
クリティカルな問題だったっぽいので早期発見できてよかったです
報告ありがとうございました。
