### ISSUE TITLE
Misskeyのアンテナのノートが重複して取得されてしまう

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1607]
# 概要
Antennaタイムライン取得のロジックのsinceIdが13.11.0で削除されてしまったため
sinceIdで取得しようとした時に初期のタイムラインが取得されてしまう。
そのため重複して同じページが読み込まれてしまうため、重複して表示される。
https://github.com/misskey-dev/misskey/commit/b53d6c7f8ca1a712eab44967e8d05a0cc7bcc034#diff-883a3f5d77794cf2344c96727836aabc74c19f57db5e2e0cd485fdb6d3af7efeL77

# 解決策
sinceIdを指定して取得しようとしたときは空のオブジェクトを返す

**Comment by futchitwo** [comment]
13.11.3 でアンテナ取得に sinceId 等が使えない問題を直したので報告しておきます
https://github.com/misskey-dev/misskey/pull/10605

**Comment by pantasystem** [comment]
なるほど不具合だったのですね
仕様変更だと思っていました。
ご報告ありがとうございます。
