### ISSUE TITLE
投稿画面のファイル選択ボタンがわかりづらいかもしれない

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1682]
# 概要
ファイルを添付することができないという誤解があったので、
現時点のアイコンはユーザにとってファイルの選択ボタンと認識しづらいアイコンなのかもしれない

**Comment by sanao1006** [comment]
`Icons.Default.AttachFile` とかどうでしょうか？
<img width="300" alt="image" src="https://github.com/pantasystem/Milktea/assets/62137820/5bf35cf8-80b8-41d8-a77c-030f211da92e">
それか`Icons.Default.Attachment`とかでもいいかもしれません
<image src="https://github.com/pantasystem/Milktea/assets/62137820/aef3cd1b-ffe6-4377-bd25-d20fd7c55c95" width="300"></image>

**Comment by pantasystem** [comment]
いいと思います
アサインしますか？

**Comment by sanao1006** [comment]
はい！お願いします🙇‍♀️

**Comment by pantasystem** [comment]
アサインしました
よろしくお願いします🙇
