### ISSUE TITLE
関係ない投稿の翻訳が表示されてしまう不具合

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1791]
# 概要
投稿の翻訳をしても、関係ない投稿の翻訳が表示されてしまうという不具合がある

**Comment by pantasystem** [comment]
ioだけで問題が発生する
今のところわかっていることとしては
Content-Typeのヘッダーを無しにして送信すると再現する

**Comment by pantasystem** [comment]
なんかContent-Type application/jsonをつけて送信するようにしたら解決した
わけがわからないね

**Comment by CyberRex0** [comment]
これ直ってないかも？

**Comment by pantasystem** [comment]
まだ反映してないですね…

**Comment by pantasystem** [comment]
製品版に反映しました

**Comment by pantasystem** [comment]
実のところ100% io側の問題なのであちら側がなんとかしてほしいところなのですがね・・・
