### ISSUE TITLE
自分がリアクションをしたかのような表示になる

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#280]
実際にはリアクションをしていないのにも関わらず、
リアクションをしたかのような表示がされる不具合が報告されている。
頻繁に発生はしていないことから特定の条件下で発生することが考えられる

**Comment by Kinoshita0623** [comment]
https://github.com/Kinoshita0623/MisskeyAndroidClient/blob/1a615a2034fc78f85c80406c5a229f00bba1480c/app/src/main/java/jp/panta/misskeyandroidclient/model/notes/NoteEventReducer.kt#L26

**Comment by Kinoshita0623** [comment]
【仮説】 
* NoteUpdated.BodyのuserIdがNullになっている。
* Account.remoteIdがNullになっている。
* onReactedの処理に問題がある

**Comment by pantasystem** [comment]
RecyclerView周りの実装に問題があることを考えたが
どの画面でも同じような不具合が発生してしまう＆再フェッチすると改善されることがあるので、
状態の異常が発生していることが考えられる。

**Comment by pantasystem** [comment]
不思議とここ最近観測されなくなったのでClose
