### ISSUE TITLE
Material you theming 

### ISSUE THREAD

**Issue by nonetrix** [pantasystem/Milktea#874]
**Is your feature request related to a problem? Please describe.**
Material you or material design 3 is the new version of material design that themes based off the wallpaper 
![Screenshot_20220929-012448](https://user-images.githubusercontent.com/45698918/192955338-c0de6fa8-7ed1-4216-b3e2-daf0b22a14e0.png)
![Screenshot_20220929-012440](https://user-images.githubusercontent.com/45698918/192955348-766341f7-2a7d-4c04-83be-17b039211b65.png)

**Describe the solution you'd like**
A rework of the UI that uses material you. This might be too big of a undertaking at such a early stage which is why it's only a suggestion 

**Describe alternatives you've considered**
Picking from material you colors while still using material 2 which seems to be possible and requires much less effort however material you isn't just color theming some overall design language tweaks also have been made

**Comment by ThatOneCalculator** [comment]
@nonetrix sorry for being off topic but what launcher is that? I love the blurry bottom bar 🤩
