### ISSUE TITLE
Recommended timeline support for Calckey instances

### ISSUE THREAD

**Issue by ThatOneCalculator** [pantasystem/Milktea#951]
If the instance runs Calckey, there's an extra timeline called `recommended` (which has the same naming conventions/endpoints as all the other timelines).

**Comment by ThatOneCalculator** [comment]
@pantasystem In addition to #568, I'll be happy to pay a ¥7000 ($50) bounty for this too :)

**Comment by ThatOneCalculator** [comment]
@pantasystem (to clarify, this is separate from 568, if you do this one I'll still be happy to pay a  ¥7000 bounty :heart: )

**Comment by pantasystem** [comment]
endpoint:
`POST api/notes/recommended-timeline`

Streaming API
`{"type":"connect","body":{"channel":"recommendedTimeline","id":"3"}}`

**Comment by pantasystem** [comment]
NodeInfoを取得するようにしたのでmisskeyなのかcalckeyなのか識別できるようになったので、
実装の準備自体は完了。

**Comment by ThatOneCalculator** [comment]
Oh, and for the bounty, do you have a donation link?
